// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PreFlight.AI.Server.Services.SQL;

namespace PreFlight.AI.Server.Migrations
{
    [DbContext(typeof(ServerDbContext))]
    [Migration("20200528014651_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PreFlightAI.Shared.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            Name = "Juneau"
                        },
                        new
                        {
                            LocationId = 2,
                            Name = "Seattle"
                        },
                        new
                        {
                            LocationId = 3,
                            Name = "Fairbanks"
                        },
                        new
                        {
                            LocationId = 4,
                            Name = "Anchorage"
                        },
                        new
                        {
                            LocationId = 5,
                            Name = "Ketchikan"
                        },
                        new
                        {
                            LocationId = 6,
                            Name = "Sitka"
                        },
                        new
                        {
                            LocationId = 7,
                            Name = "Wrangell"
                        },
                        new
                        {
                            LocationId = 8,
                            Name = "Petersburg"
                        });
                });

            modelBuilder.Entity("PreFlightAI.Shared.Weather", b =>
                {
                    b.Property<int>("weatherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AirPressure")
                        .HasColumnType("float");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.Property<double>("WeightValue")
                        .HasColumnType("float");

                    b.Property<string>("weatherLink")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("weatherID");

                    b.ToTable("Weathers");

                    b.HasData(
                        new
                        {
                            weatherID = 1,
                            AirPressure = 1.0,
                            Temperature = 60.0,
                            WeightValue = 6.7000000000000002
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
